### ISSUE TITLE
assert self.active_learner, "Please initialize with the sample method"

### ISSUE THREAD

**Issue by Gandharv30** [Lyonk71/pandas-dedupe#29]
I am using pandas_dedupe=1.3.1 and dedupe=2.0.0. I don't know why I get this error :
File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/__init__.py", line 86, in dedupe_dataframe
    deduper.sample(data_d, 15000)
AttributeError: 'Dedupe' object has no attribute 'sample'

**Comment by Gandharv30** [comment]
After updating pandas_dedupe tp 1.3.1 and dedupe to 2.0.3 I am getting this error after labeling some of the examples:
assert self.active_learner, "Please initialize with the sample method"
File "./dedupStatic.py", line 12, in <module>
    df_final=dedupe_dataframe(df,['firstname','lastname'])
  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py", line 242, in dedupe_dataframe
    sample_size, update_model)
  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py", line 105, in _train
    deduper = _active_learning(data, sample_size, deduper, training_file, settings_file)
  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py", line 45, in _active_learning
    dedupe.console_label(deduper)
  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/convenience.py", line 43, in console_label
    uncertain_pairs = deduper.uncertain_pairs()
  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py", line 1117, in uncertain_pairs
    assert self.active_learner, "Please initialize with the sample method"
AssertionError: Please initialize with the sample method

**Comment by ieriii** [comment]
Hi,

the default `sample_size` used during active learning is `0.3`.
Once you labelled all the records in the sample, dedupe returns this error.

To avoid this, you might want to set `sample_size=1`.
Note: you might still incur in this error whenever the number of examples you have labelled hits the total number of examples in your dataframe.

**Comment by Gandharv30** [comment]
Hi, Since I am using pandas_dedupe library, where do I set sample size in that?

**Comment by Gandharv30** [comment]
Thanks, Enrico for taking out time to help me solve the issue. i tried to
set sample_size by passing it 1 in dedup_dataframe function present in the
site package. Now, i am successfully able to label 10 positive and 10
negative examples. But when i press finish this is the error i get:

Traceback (most recent call last):

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 106, in score

    self.num_cores)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/core.py",
line 237, in scoreDuplicates

    process.start()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/process.py",
line 105, in start

    self._popen = self._Popen(self)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/context.py",
line 284, in _Popen

    return Popen(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 32, in __init__

    super().__init__(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_fork.py",
line 19, in __init__

    self._launch(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 42, in _launch

    prep_data = spawn.get_preparation_data(process_obj._name)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 143, in get_preparation_data

    _check_not_importing_main()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 136, in _check_not_importing_main

    is not going to be frozen to produce an executable.''')

RuntimeError:

        An attempt has been made to start a new process before the

        current process has finished its bootstrapping phase.


        This probably means that you are not using fork to start your

        child processes and you have forgotten to use the proper idiom

        in the main module:


            if __name__ == '__main__':

                freeze_support()

                ...


        The "freeze_support()" line can be omitted if the program

        is not going to be frozen to produce an executable.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 105, in spawn_main

    exitcode = _main(fd)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 114, in _main

    prepare(preparation_data)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 225, in prepare

    _fixup_main_from_path(data['init_main_from_path'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 277, in _fixup_main_from_path

    run_name="__mp_main__")

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
263, in run_path

    pkg_name=pkg_name, script_name=fname)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
96, in _run_module_code

    mod_name, mod_spec, pkg_name, script_name)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
85, in _run_code

    exec(code, run_globals)

  File
"/Users/gandharv/Desktop/OfficeWork/Deupe/pandas_dedupe/dedupStatic.py",
line 12, in <module>

    df_final=dedupe_dataframe(df,['Company Name'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 245, in dedupe_dataframe

    clustered_df = _cluster(deduper, data_d, threshold, canonicalize)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 143, in _cluster

    clustered_dupes = deduper.partition(data, threshold)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 170, in partition

    pair_scores = self.score(pairs)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 112, in score


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods''
')

RuntimeError:

                You need to either turn off multiprocessing or protect

                the calls to the Dedupe methods with a

                `if __name__ == '__main__'` in your main module, see


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

Traceback (most recent call last):

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 106, in score

    self.num_cores)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/core.py",
line 237, in scoreDuplicates

    process.start()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/process.py",
line 105, in start

    self._popen = self._Popen(self)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/context.py",
line 284, in _Popen

    return Popen(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 32, in __init__

    super().__init__(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_fork.py",
line 19, in __init__

    self._launch(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 42, in _launch

    prep_data = spawn.get_preparation_data(process_obj._name)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 143, in get_preparation_data

    _check_not_importing_main()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 136, in _check_not_importing_main

    is not going to be frozen to produce an executable.''')

RuntimeError:

        An attempt has been made to start a new process before the

        current process has finished its bootstrapping phase.


        This probably means that you are not using fork to start your

        child processes and you have forgotten to use the proper idiom

        in the main module:


            if __name__ == '__main__':

                freeze_support()

                ...


        The "freeze_support()" line can be omitReading from
dedupe_dataframe_learned_settings

Clustering...

ted if the program

        is not going to be frozen to produce an executable.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 105, in spawn_main

    exitcode = _main(fd)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 114, in _main

    prepare(preparation_data)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 225, in prepare

Traceback (most recent call last):

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 106, in score

    self.num_cores)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/core.py",
line 237, in scoreDuplicates

    process.start()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/process.py",
line 105, in start

    self._popen = self._Popen(self)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/context.py",
line 284, in _Popen

    return Popen(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 32, in __init__

    super().__init__(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_fork.py",
line 19, in __init__

    self._launch(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 42, in _launch

    prep_data = spawn.get_preparation_data(process_obj._name)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 143, in get_preparation_data

    _check_not_importing_main()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 136, in _check_not_importing_main

    is not going to be frozen to produce an executable.''')

RuntimeError:

        An attempt has been made to start a new process before the

        current process has finished its bootstrapping phase.


        This probably means that you are not using fork to start your

        child processes and you have forgotten to use the proper idiom

        in the main module:


            if __name__ == '__main__':

                freeze_support()

                ...


        The "freeze_support()" line can be omitted if the program

        is not going to be frozen to produce an executable.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 105, in spawn_main

    exitcode = _main(fd)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 114, in _main

    prepare(preparation_data)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 225, in prepare

    _fixup_main_from_path(data['init_main_from_path'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 277, in _fixup_main_from_path

    run_name="__mp_main__")

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
263, in run_path

    pkg_name=pkg_name, script_name=fname)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
96, in _run_module_code

    mod_name, mod_spec, pkg_name, script_name)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
85, in _run_code

    exec(code, run_globals)

  File
"/Users/gandharv/Desktop/OfficeWork/Deupe/pandas_dedupe/dedupStatic.py",
line 12, in <module>

    df_final=dedupe_dataframe(df,['Company Name'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 245, in dedupe_dataframe

    clustered_df = _cluster(deduper, data_d, threshold, canonicalize)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 143, in _cluster

    clustered_dupes = deduper.partition(data, threshold)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 170, in partition

    pair_scores = self.score(pairs)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 112, in score


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods''
')

RuntimeError:

                You need to either turn off multiprocessing or protect

                the calls to the Dedupe methods with a

                `if __name__ == '__main__'` in your main module, see


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

    _fixup_main_from_path(data['init_main_from_path'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 277, in _fixup_main_from_path

    run_name="__mp_main__")

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
263, in run_path

Traceback (most recent call last):

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 106, in score

    self.num_cores)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/core.py",
line 237, in scoreDuplicates

    process.start()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/process.py",
line 105, in start

    self._popen = self._Popen(self)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/context.py",
line 284, in _Popen

    return Popen(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 32, in __init__

    super().__init__(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_fork.py",
line 19, in __init__

    self._launch(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 42, in _launch

    prep_data = spawn.get_preparation_data(process_obj._name)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 143, in get_preparation_data

    _check_not_importing_main()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 136, in _check_not_importing_main

    is not going to be frozen to produce an executable.''')

RuntimeError:

        An attempt has been made to start a new process before the

        current process has finished its bootstrapping phase.


        This probably means that you are not using fork to start your

        child processes and you have forgotten to use the proper idiom

        in the main module:


            if __name__ == '__main__':

                freeze_support()

                ...


        The "freeze_support()" line can be omitted if the program

        is not going to be frozen to produce an executable.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 105, in spawn_    pkg_name=pkg_name, script_name=fname)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
96, in _run_module_code

    mod_name, mod_spec, pkg_name, script_name)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
85, in _run_code

    exec(code, run_globals)

  File
"/Users/gandharv/Desktop/OfficeWork/Deupe/pandas_dedupe/dedupStatic.py",
line 12, in <module>

    df_final=dedupe_dataframe(df,['Company Name'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 245, in dedupe_dataframe

    clustered_df = _cluster(deduper, data_d, threshold, canonicalize)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 143, in _cluster

    clustered_dupes = deduper.partition(data, threshold)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 170, in partition

    pair_scores = self.score(pairs)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 112, in score


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods''
')

RuntimeError:

                You need to either turn off multiprocessing or protect

                the calls to the Dedupe methods with a

                `if __name__ == '__main__'` in your main module, see


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

main

    exitcode = _main(fd)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 114, in _main

    prepare(preparation_data)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 225, in prepare

    _fixup_main_from_path(data['init_main_from_path'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 277, in _fixup_main_from_path

    run_name="__mp_main__")

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
263, in run_path

    pkg_name=pkg_name, script_name=fname)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
96, in _run_module_code

    mod_name, mod_spec, pkg_name, script_name)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
85, in _run_code

    exec(code, run_globals)

  File
"/Users/gandharv/Desktop/OfficeWork/Deupe/pandas_dedupe/dedupStatic.py",
line 12, in <module>

    df_final=dedupe_dataframe(df,['Company Name'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 245, in dedupe_dataframe

    clustered_df = _cluster(deduper, data_d, threshold, canonicalize)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 143, in _cluster

    clustered_dupes = deduper.partition(data, threshold)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 170, in partition

    pair_scores = self.score(pairs)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 112, in score


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods''
')

RuntimeError:

                You need to either turn off multiprocessing or protect

                the calls to the Dedupe methods with a

                `if __name__ == '__main__'` in your main module, see


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

Traceback (most recent call last):

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 106, in score

    self.num_cores)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/core.py",
line 237, in scoreDuplicates

    process.start()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/process.py",
line 105, in start

    self._popen = self._Popen(self)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/context.py",
line 284, in _Popen

    return Popen(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 32, in __init__

    super().__init__(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_fork.py",
line 19, in __init__

    self._launch(process_obj)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py",
line 42, in _launch

    prep_data = spawn.get_preparation_data(process_obj._name)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 143, in get_preparation_data

    _check_not_importing_main()

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 136, in _check_not_importing_main

    is not going to be frozen to produce an executable.''')

RuntimeError:

        An attempt has been made to start a new process before the

        current process has finished its bootstrapping phase.


        This probably means that you are not using fork to start your

        child processes and you have forgotten to use the proper idiom

        in the main module:


            if __name__ == '__main__':

                freeze_support()

                ...


        The "freeze_support()" line can be omitted if the program

        is not going to be frozen to produce an executable.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 105, in spawn_main

    exitcode = _main(fd)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 114, in _main

    prepare(preparation_data)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 225, in prepare

    _fixup_main_from_path(data['init_main_from_path'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/spawn.py",
line 277, in _fixup_main_from_path

    run_name="__mp_main__")

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
263, in run_path

    pkg_name=pkg_name, script_name=fname)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
96, in _run_module_code

    mod_name, mod_spec, pkg_name, script_name)

  File "/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line
85, in _run_code

    exec(code, run_globals)

  File
"/Users/gandharv/Desktop/OfficeWork/Deupe/pandas_dedupe/dedupStatic.py",
line 12, in <module>

    df_final=dedupe_dataframe(df,['Company Name'])

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 245, in dedupe_dataframe

    clustered_df = _cluster(deduper, data_d, threshold, canonicalize)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas_dedupe/dedupe_dataframe.py",
line 143, in _cluster

    clustered_dupes = deduper.partition(data, threshold)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 170, in partition

    pair_scores = self.score(pairs)

  File
"/Users/gandharv/.pyenv/versions/3.6.8/lib/python3.6/site-packages/dedupe/api.py",
line 112, in score


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods''
')

RuntimeError:

                You need to either turn off multiprocessing or protect

                the calls to the Dedupe methods with a

                `if __name__ == '__main__'` in your main module, see


https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

I Hope, you will help me out!

**Comment by ieriii** [comment]
Happy to help, @Gandharv30.
It would be better if you could provide a reproducible example (small dataframe and simple script).
This would help us to understand whether it is an issue related to the library of a bug in your code.

**Comment by Gandharv30** [comment]
Shall I email it to you?
Or shall i post it here?

**Comment by ieriii** [comment]
if you think it is an bug in pandas-dedupe library, you can post the minimal reproducible example code here.
If you think it is a bug in your code, stackoverflow is the best place to post your question.

**Comment by Gandharv30** [comment]
I think its a bug in the library because the code works fine with pandas_dedupe==0.21 and dedupe==1.10.0. I have tested it. The only problem I am getting with those versions is that even after correctly labeling the examples, it fails to identify all the clusters. it always leaves behind on cluster unidentified

**Comment by Gandharv30** [comment]
import pandas as pd
from pandas_dedupe import dedupe_dataframe
df=pd.read_csv('sample.csv')
df_final=dedupe_dataframe(df,['firstname','lastname'])
df_final.to_csv('sample_deduped.csv')


Sample contains:

firstname | lastname
-- | --
akash | gupta
vinay | sharma
vinay | s
shikhar | dhawan
gandharv | p
g | pathak
a | gupta
vikramadita | ganguly

**Comment by ieriii** [comment]
I cannot reproduce the error with the example you provided. See my  output below.

```
import pandas as pd
from pandas_dedupe import dedupe_dataframe

df = pd.DataFrame.from_dict({'firstname':['akash', 'vinay', 'vinay', 'shikhar', 'gandharv', 'g'], 'lastname':['gupta', 'sharma', 's', 'dhawan', 'p', 'pathak']})

df_final=dedupe_dataframe(df,['firstname','lastname'], sample_size=1)
print(df_final)

# Output
# 	firstname	lastname	cluster id	confidence
# 0	akash	gupta	1	1.000000
# 1	vinay	sharma	0	0.999975
# 2	vinay	s	0	0.999975
# 3	shikhar	dhawan	2	1.000000
# 4	gandharv	p	3	1.000000
# 5	g	pathak	4	1.000000
```
In general, not all observations are necesarily assigned to a cluster.
I would suggest you to had a close look to the [dedupe docs](https://dedupe.io/documentation/how-it-works.html)

**Comment by Gandharv30** [comment]
what version are you using for the two libraries? @ieriii . I tried it on two machines resulting in the same error!

**Comment by ieriii** [comment]
I'm very sorry but without a reproducible example, we cannot help much.

It seems you are having issues with `num_cores` which runs dedupe on all available cores when set to `None` - `None` is the default and we do not offer the possibility to set to other numbers at the moment).
